### ISSUE TITLE
네이버 오픈프로젝트 백업 오류

### ISSUE THREAD

**Issue by JoonmoKim** [naver/devcenter-open-project-migration#6]
![image](https://cloud.githubusercontent.com/assets/23396244/20207544/57ebfe52-a82b-11e6-9d45-68953214903a.png)
네이버 오픈프로젝트 백업 진행시 npa 사용할 때 백업파일이 다운로드 되지 않는 오류가 있습니다.

아래의 URL에서 안내되어 있는 순서대로 진행하였는데, 문제점이 무엇인지 찾지 못하였습니다.

URL)
https://github.com/naver/devcenter-open-project-migration

도움주시면 감사하겠습니다.

OS Version : Windows 10 Pro (64-bit) 14393.447
Python Version : 3.5.2 (64-bit)
Pip Version : 9.0.1

**Comment by maxtortime** [comment]
https://github.com/naver/devcenter-open-project-migration#비공개-프로젝트-준비-작업
를 참고하셔서 생성하신 `cookies.txt`가 유효한지 다시 살펴주세요.

쿠키 파일이 유효함에도 아무것도 다운로드 되지 않으셨다면 다시 문의주시면 감사하겠습니다.

**Comment by maxtortime** [comment]
혹시 프로젝트에 아무 이슈나 게시판 글도 올라가 있지 않다면 아무것도 다운로드 되지 않습니다.
바로 다음 단계로 넘어가셔도 무방합니다.

**Comment by JoonmoKim** [comment]
답변 감사합니다.
제 경우는 이슈, 게시판에 글이 없는 관계로 아무것도 다운로드 되지 않은 것으로 확인하였습니다.
프로젝트 코드와 리비전 히스토리만 옮기면 되는 경우인지라 아래 한가지만 진행하면 되는 것이었습니다. 
https://github.com/naver/devcenter-open-project-migration#소스-코드-import-코드-저장소가-있으면서-코드들을-github로-옮기려는-경우만-본-step을-실행해-주세요

이후에 안드로이드 스튜디오와 Github만 연동시키니 잘 동작합니다. 감사합니다.

**Comment by maxtortime** [comment]
네 잘 옮기셨다니 감사합니다. 이 이슈는 닫겠습니다. ㅎㅎ
